### ISSUE TITLE
Checks for 403 Status codes

### ISSUE THREAD

**Issue by perfectlylogical** [0xsauby/yasuo#11]
Hey, 

I have noticed that sometimes a app returns a 403 instead of the expected 401, example in jenkins when the /script url requires authentication it returns a 403 error, should we be capturing these cases in the identification of services to either brute force later or atleast make a not in yasuo in case they have some low level creds they can try

**Comment by 0xsauby** [comment]
These 403s will be automatically handled by Mechanize.

**Comment by perfectlylogical** [comment]
403's not 30x's. 
The find_vulnerable_applications function has a case for 200, 401, and 404 status codes and how to handle 301's but not 403, like I said this is filed because I saw it not detect Jenkins when the script console was authenticated, and in that case the server responded with a 403 code.

**Comment by perfectlylogical** [comment]
Merged with #10
