### ISSUE TITLE
Windows do not have /dev/null

### ISSUE THREAD

**Issue by fuuddanni** [0xsauby/yasuo#16]
I, [2015-05-29T19:42:13.741321 #272]  INFO -- : Initiating port scan
C:/Users/Besitzer/Documents/GitHub/yasuo/yasuo.rb:119:in `reopen': No such file or directory - /dev/null (Errno::ENOENT)

        from C:/Users/Besitzer/Documents/GitHub/yasuo/yasuo.rb:119:in `nmap_scan'
        from C:/Users/Besitzer/Documents/GitHub/yasuo/yasuo.rb:104:in `run'
        from C:/Users/Besitzer/Documents/GitHub/yasuo/yasuo.rb:574:in `<main>'

C:\Users\Besitzer\Documents\GitHub\yasuo>

Is is possible to port this script in windows?

**Comment by 0xsauby** [comment]
Hey, we've tested it extensively on *nix systems but not on windows. I can look into porting it to windows but it'll take a while. In the meantime, you can install and run it on Kali Linux VM.

**Comment by fuuddanni** [comment]
That sounds good. Thanks a lot for your attention. I´ll run your script in Kali too.

**Comment by KINGSABRI** [comment]
Hi you can use a temp file instead of `/dev/null` then delete it(if you want). 

```ruby
$stdout.reopen("tmp.log", "w")
File.delete "tmp.log"
```

**Comment by 0xsauby** [comment]
I don't think I'd have time anytime soon to work on a windows build.
