### ISSUE TITLE
Error and more

### ISSUE THREAD

**Issue by KINGSABRI** [0xsauby/yasuo#17]
Hi, when running the script against some target it rises the the following error 

```
`block (2 levels) in find_vulnerable_applications': undefined method `code' for nil:NilClass (NoMethodError)
from ./yasuo.rb:282:in `each'
from ./yasuo.rb:282:in `each_with_index'
from ./yasuo.rb:282:in `block in find_vulnerable_applications'
from ./yasuo.rb:276:in `each_key'
from ./yasuo.rb:276:in `find_vulnerable_applications'
from ./yasuo.rb:192:in `block (2 levels) in process_nmap_scan'
```
the error is the follwowing line 

https://github.com/0xsauby/yasuo/blob/master/yasuo.rb#L291

That's because `resp` getting nil value 

you can place the following before it to debug

```ruby
        if resp.nil?
          puts "[+] Oooops!".red.bold
          pp attack_url
          pp resp
          pp resp.body
          puts "Exiting!!!!\n\n\n".red
          exit 0
        end
```

another thing ,, you're using colorize gem which is great gem but it lot more than what you need 

you can just place the following at the beginning and add what you need

```ruby
class String
  def red; colorize(self, "\e[1m\e[31m"); end
  def green; colorize(self, "\e[1m\e[32m"); end
  def dark_green; colorize(self, "\e[32m"); end
  def yellow; colorize(self, "\e[1m\e[33m"); end
  def blue; colorize(self, "\e[1m\e[34m"); end
  def dark_blue; colorize(self, "\e[34m"); end
  def purple; colorize(self, "\e[35m"); end
  def dark_purple; colorize(self, "\e[1;35m"); end
  def cyan; colorize(self, "\e[1;36m"); end
  def dark_cyan; colorize(self, "\e[36m"); end
  def pure; colorize(self, "\e[1m\e[35m"); end
  def bold; colorize(self, "\e[1m"); end
  def colorize(text, color_code)  "#{color_code}#{text}\e[0m" end
end
```

use it as colorize gem 
```ruby
puts "RubyFu".red
puts "RubyFu".green
puts "RubyFu".yellow.bold
```

I was trying to contribute more effectively but it got hit by punch of tasks :D 
more usefull things in RubyFu book (http://kingsabri.gitbooks.io/rubyfu)

HTH
Regards and respect

**Comment by 0xsauby** [comment]
I thought I fixed that resp returning nil bug. Apparently not.
Thanks for the recommendation regarding colorize gem. Much better. I'll implement all this today, hopefully. Thanks again.

**Comment by enderax** [comment]
Hi,
I got same error:
<pre><code>
I, [2015-06-16T11:42:30.912541 #111765]  INFO -- : Discovered open port: 172.16.15.248:8080
I, [2015-06-16T11:42:30.975298 #111765]  INFO -- : <<<Enumerating vulnerable applications>>>
Yasuo found an unauthenticated instance of Apache Tomcat at http://172.16.15.248:8080/manager.
yasuo.rb:291:in `block (2 levels) in find_vulnerable_applications': undefined method `code' for nil:NilClass (NoMethodError)
	from yasuo.rb:282:in `each'
	from yasuo.rb:282:in `each_with_index'
	from yasuo.rb:282:in `block in find_vulnerable_applications'
	from yasuo.rb:276:in `each_key'
	from yasuo.rb:276:in `find_vulnerable_applications'
	from yasuo.rb:192:in `block (2 levels) in process_nmap_scan'
</code></pre>

And there is an false positive in it. The running service is actually Asterisk/1.4.19.

**Comment by 0xsauby** [comment]
I have fixed this issue. Please test and let me know if you are still having issues. There may be some false positives every now and then if the application signatures are same for 2 or more apps.
