### ISSUE TITLE
Mechanize gem requires rake

### ISSUE THREAD

**Issue by shpendk** [0xsauby/yasuo#23]
This is really minor but in a clean installation of Kali Linux, the script failes to run because mechanize isn't installed. Mechanize itself fails to install because rake is not there.

I'd suggest to update the readme and include rake in the list of needed gems. Otherwise great tool, thanks for sharing !

**Comment by 0xsauby** [comment]
Thanks for reporting this. I did some digging on this. Mechanize requires Nokogiri, which has a dependency on rake. Rake is required by many other tools to work. If you bundle install, you should be good. Lemme know if there are any other issues.
