### ISSUE TITLE
Yasuo bombs on base Kali 2 instance

### ISSUE THREAD

**Issue by mchilty** [0xsauby/yasuo#24]
Hi there, 

Have relied on Yasuo when using Kali 1, but perhaps the new ruby (2.1.5p273) doesn't play nicely.  Have also tried 2.2.1 with same results.  Errors out as follows when trying to use Nmap .xml file.  Scanning (-r) doesn't error out as such but fails to find any hosts to enumerate despite testing against systems/URI in signatures.yaml

I, [2015-12-30T21:19:31.335262 #90094]  INFO -- : Using nmap scan output file test.xml
I, [2015-12-30T21:19:31.336562 #90094]  INFO -- : Discovered open port: 192.168.2.1:80
I, [2015-12-30T21:19:31.350428 #90094]  INFO -- : Discovered open port: 192.168.2.1:443
yasuo/yasuo.rb:229:in `block (2 levels) in detect_targets': undefined method `ssl?' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.1.0/gems/ruby-nmap-0.8.0/lib/nmap/host.rb:382:in `block in each_port'
	from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `block in each'
	from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:236:in `upto'
	from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:236:in `each'
	from /var/lib/gems/2.1.0/gems/ruby-nmap-0.8.0/lib/nmap/host.rb:381:in `each_port'
	from yasuo/yasuo.rb:227:in `block in detect_targets'
	from yasuo/yasuo.rb:223:in `each'
	from yasuo/yasuo.rb:223:in `detect_targets'
	from yasuo/yasuo.rb:167:in `block (2 levels) in process_nmap_scan'

Hope this helps and thanks!

**Comment by 0xsauby** [comment]
Hey, thanks for reporting this issue. Can you check if you get the same error while running Yasuo on your older instance of Kali?

**Comment by mchilty** [comment]
I have never seen this error in Kali 1/1.1 (ruby 1.9.3p194) and have used Yasuo 2.0 since its release. 
Thanks for looking into this -- I appreciate it!

**Comment by perfectlylogical** [comment]
Hi we made some slight changes to the condition for the check can you pull the latest version and see if it works? 

If it doesn't maybe a gem is there but not the most up to date version thinking specifically the ruby-nmap gem, would it be possible to see the gems installed for your ruby environment using the command, gem list --local.

**Comment by mchilty** [comment]
Hi,

I did test the new version and had the same results, but did some further testing/review and made an interesting discovery.  The problem is being caused by a malformed Nmap XML file that contains a single port element block that lacks the "service name" element (see below -- second entry)

<port protocol="tcp" portid="8123"><state state="open" reason="syn-ack" reason_ttl="0"/><service name="tcpwrapped" method="probed" conf="8"/></port>

<port protocol="tcp" portid="17123"><state state="open" reason="syn-ack" reason_ttl="0"/></port>

<port protocol="tcp" portid="27123"><state state="open" reason="syn-ack" reason_ttl="0"/><service name="unknown" tunnel="ssl" method="table" conf="3"/></port>


No idea why Nmap isn't stamping it "unknown due to probe/table lookup failure, but this effectively causes Yasuo to bomb.  Creating an entry in the /usr/share/nmap/nmap-services table is a temp workaround.

**Comment by 0xsauby** [comment]
Thanks for the detailed info. Would it be possible for you to send us the nmap xml output after masking the real IP address. I think I have a fair idea about whats going on.

**Comment by mchilty** [comment]
Here you go -- thanks for looking into this.

**Comment by 0xsauby** [comment]
Alright, can you checkout the code from branch "damnbugs" and see if it solves the issue. please let us know.

**Comment by mchilty** [comment]
Hey there,

Solved the issue!  I'll wait for the official release to put it into
production for us.  Can you explain why Nmap might be leaving that element
out?

thanks,

Matthew

**Comment by 0xsauby** [comment]
Probably because it could not deduce the service on that port.
I've merged the changes to master branch. Thanks for playing along :8ball:
