### ISSUE TITLE
response.rb:380:in `inflate': incorrect header check (Zlib::DataError)

### ISSUE THREAD

**Issue by P1ro** [0xsauby/yasuo#26]
this is the error ill get whe try to scan one subnet:
/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:380:in `inflate': incorrect header check (Zlib::DataError)
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:380:in `block in inflate_adapter'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:411:in `call_block'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:402:in `<<'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:108:in `read'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:402:in `read'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:291:in `block in read_body_0'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:262:in `inflater'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:281:in `read_body_0'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:202:in `read_body'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:227:in `body'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:164:in `reading_body'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1445:in `transport_request'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1407:in `request'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
        from /home/p1ro/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1398:in `request'
        from ./yasuo.rb:498:in `httpGETRequest'
        from ./yasuo.rb:312:in `block (3 levels) in detect_targets'
        from ./yasuo.rb:303:in `each'
        from ./yasuo.rb:303:in `block (2 levels) in detect_targets'
        from /home/p1ro/.rvm/gems/ruby-2.3.1/gems/ruby-nmap-0.9.1/lib/nmap/host.rb:384:in `block in each_port'
        from /home/p1ro/.rvm/gems/ruby-2.3.1/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
        from /home/p1ro/.rvm/gems/ruby-2.3.1/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
        from /home/p1ro/.rvm/gems/ruby-2.3.1/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
        from /home/p1ro/.rvm/gems/ruby-2.3.1/gems/ruby-nmap-0.9.1/lib/nmap/host.rb:383:in `each_port'
        from ./yasuo.rb:280:in `block in detect_targets'
        from ./yasuo.rb:276:in `each'
        from ./yasuo.rb:276:in `detect_targets'
        from ./yasuo.rb:217:in `block (2 levels) in process_nmap_scan'

**Comment by 0xsauby** [comment]
Hey, can you please tell me a bit about your setup. Are you running it on Kali Linux? Also, if you could be let me know the command-line arguments you're using with Yasuo. Thanks.

**Comment by P1ro** [comment]
thanks for the answer,
Linux PPArch 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU/Linux
using yasuo git v2.1
i have try a few commands -f 192.168.0.0/16 or -r with nmap xml output also the -pD dont work or the -f with ip_list (one ip per line) says unresolve host for the -f /path/to/file_ips 
If i try a small list of ips or a single host it does work, or maybe some specific hosts or services are breaking it.
Later.

**Comment by 0xsauby** [comment]
Hi, I believe you might be using the wrong command line options.
- If you want to run Yasuo against a network range, use:
./yasuo.rb -r x.x.x.0/24

- If you want to run Yasuo against an nmap output file, use:
./yasuo.rb -f nmap_output.xml
either copy the nmap_output.xml to the same directory as Yasuo or provide path to the file.

Add switch "-b all" if you would like to brute-force logins of discovered apps. Something like:
./yasuo.rb -f nmap_output.xml -b all

**Comment by P1ro** [comment]
Hi, thanks, but yes i can run agains network range with -r x.x.x.0/24 or nmap xml only with -r nmap_file.xml
but wondering if there is an option for a ip list?
also i cant find the exact host that breaking the run.

**Comment by 0xsauby** [comment]
Yasuo does not support ip list input as of now but I plan to work on it soon. If you have a list of IPs, please use nmap to perform the port scan and then feed the xml output to Yasuo with "-f" switch. Also, look at the Yasuo log file "yasuo_output_XXXXXXXXUTC.log" to see which host it scanned last, before crashing. Then browse to that ip:port manually to see if there are any obvious issues. Do keep me posted.
