### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by bucky67gto** [0xsauby/yasuo#31]
./yasuo.rb:232:in `each_slice': invalid slice size (ArgumentError)
	from ./yasuo.rb:232:in `process_nmap_scan'
	from ./yasuo.rb:132:in `run'
	from ./yasuo.rb:700:in `<main>'

**Comment by sdcampbell** [comment]
I just got the same error... after one successful run on a different network subnet.

**Comment by 0xsauby** [comment]
Are you still getting this error? Can you provide some more info on what command line arguments you're using with Yasuo.

**Comment by sdcampbell** [comment]
I think that the error was because the subnet I scanned was empty. I've used it since then on a subnet with live hosts and didn't get an error.

**Comment by 0xsauby** [comment]
Perfect, in that case, I'll close this issue.
