### ISSUE TITLE
kernel_require.rb:59:in `require': cannot load such file -- text-table (LoadError)

### ISSUE THREAD

**Issue by 1N3** [0xsauby/yasuo#33]
Started receiving this error recently even though yasuo was working fine for the longest time:
```
./yasuo.rb                                                                                                                                                                                    127 ↵ ──(Thu,May10)─┘
Traceback (most recent call last):
	2: from ./yasuo.rb:29:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- text-table (LoadError)
```

Any ideas? Tried rebuilding and reinstalling the gems but no luck.

**Comment by 0xsauby** [comment]
Looks like you're missing the text-table gem. "gem install text-table" should fix it.

**Comment by 1N3** [comment]
Awesome, thanks! That worked.

**Comment by xnurexm** [comment]
you can help me bro... this my problem

Traceback (most recent call last):
        2: from wpscan.rb:16:in `<main>'
        1: from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:122:in `require'
/usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:122:in `require': cannot load such file -- wpscan/helper (LoadError)

**Comment by 0xsauby** [comment]
This error is thrown by Yasuo? Can you tell me a little bit more about what you're to do?

**Comment by xnurexm** [comment]
I tried to install it on ubuntu 14.04 [cloud9]

**Comment by 0xsauby** [comment]
Can you try the following and let me know if it works:
sudo apt-get install zlib1g-dev libsqlite3-dev
bundle install --path vendor --gemfile ./Gemfile

**Comment by dz3nan** [comment]
1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ubygems (LoadError)

Hello this is my problem, can you help me?

**Comment by 0xsauby** [comment]
Have you already performed the following steps and installed all required gems:
sudo apt-get install zlib1g-dev libsqlite3-dev
bundle install --path vendor --gemfile ./Gemfile

**Comment by pavlosemegen** [comment]
> Have you already performed the following steps and installed all required gems:
> sudo apt-get install zlib1g-dev libsqlite3-dev
> bundle install --path vendor --gemfile ./Gemfile

Hello,
I have a ruby script, if I run it from command line it works, but when I configure cron task for running it automatically it doesn't work and I get the same error message. It's strange for me. Have you struggled with smth like this?
Thanks

**Comment by Jupitergit101** [comment]
i have mac but i receive the error 

1: from /Users/mubasharhassan/.rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/mubasharhassan/.rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- watir (LoadError)

any thought please help?

**Comment by imdoey** [comment]
> i have mac but i receive the error
> 
> 1: from /Users/mubasharhassan/.rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require' /Users/mubasharhassan/.rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- watir (LoadError)
> 
> any thought please help?

I'm having the exact same problem. Have you figured it out?

**Comment by 0xsauby** [comment]
@Jupitergit101 @imdoey I have not tested Yasuo on Mac osx. Please use Kali Linux if possible.

**Comment by Keulsss** [comment]
i've same problem when i run `heroku run rails db:migrate`

**Comment by akarsh70177** [comment]
Started receiving this error recently

Traceback (most recent call last):
        2: from apk-embed-payload.rb:9:in `<main>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- colorize (LoadError)

**Comment by cybernaima** [comment]
Hey sorry to re-open this issue but I am also having the same problem as original poster. I've tried the suggestion given and its still not working for me 

![image](https://user-images.githubusercontent.com/91866913/136117148-5f0b956f-2b81-4e84-816e-442c0eb86eb2.png)

**Comment by Prithivi-Raj** [comment]
I am trying to run require command to implement the usage of a module, I'm not able to do it tho! Getting the same error

**Comment by danicunhac** [comment]
Hi, I had quite the same error but it was regarding `spaceship` instead of `text-table`.
By following the log files I discovered that I was missing a ruby `config.h` file inside `usr/include`. Basically I had to create a link from `config.h` inside Headers to the same folder inside `usr/include`.

```bash
cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby
ln -sf ../../../../Headers/ruby/config.h
```
I followed this answer on Stackoverflow:
https://stackoverflow.com/questions/53135863/macos-mojave-ruby-config-h-file-not-found/65481787#65481787

**Note that it says it's for macOS Mojave, but this happened to me on Monterey**

**Comment by Ismailsarhir** [comment]
Started receiving this error when i run the commande compass watch !!


LoadError on line ["92"] of /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- bootstrap-sass
Run with --trace to see the full backtrace
