### ISSUE TITLE
no such file to load -- colorize

### ISSUE THREAD

**Issue by baalpeteor** [0xsauby/yasuo#7]
after running the gem install line (which includes colorize) and running gem install colorize on it's own, and even downloading colorize (the latest) and installing it manually, when i run ./yasuo.rb I get:

./yasuo.rb:22:in `require': no such file to laod -- colorize (LoadError)
             from ./yasuo.rb:22
#

how do I fix this?

**Comment by kkd927** [comment]
Plz verify you type 'gem install colorize'. If you run with 'sudo gem install colorize', colorize gem is installed in root env not current user's env.

**Comment by 0xsauby** [comment]
Latest version of Yasuo does not use colorize gem so you don't to install it anymore.

**Comment by mochadwi** [comment]
> gem install colorize

It's not work. Still no such file to load

**Comment by 0xsauby** [comment]
@mochadwi Can you provide some information about your OS?
